//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Net_2.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CAR_MANAGEREntities : DbContext
    {
        public CAR_MANAGEREntities()
            : base("name=CAR_MANAGEREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CNC> CNC { get; set; }
        public virtual DbSet<Comunas> Comunas { get; set; }
        public virtual DbSet<MARCAS_vhs> MARCAS_vhs { get; set; }
        public virtual DbSet<region> region { get; set; }
        public virtual DbSet<STOCK> STOCK { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TIP_PAG> TIP_PAG { get; set; }
        public virtual DbSet<Tip_Pagos> Tip_Pagos { get; set; }
        public virtual DbSet<tip_vhs> tip_vhs { get; set; }
        public virtual DbSet<TIPO_USR> TIPO_USR { get; set; }
        public virtual DbSet<usr_sis> usr_sis { get; set; }
        public virtual DbSet<VENTAS_VHS> VENTAS_VHS { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
