//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Net_2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public string Nombre_usr { get; set; }
        public int identi_usr { get; set; }
        public string apellido_ptn { get; set; }
        public string apellido_mtn { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> Comuna { get; set; }
        public Nullable<int> Region { get; set; }
        public Nullable<int> Tipo_usr { get; set; }
    
        public virtual Comunas Comunas { get; set; }
        public virtual region region1 { get; set; }
        public virtual TIPO_USR TIPO_USR1 { get; set; }
    }
}
